layout_spectrum: 0.5803273350466043
typography_spectrum: 0.28191541880369186
color:
  saturation: 0.6859882173594087
  brandStrength: 0.9271411211229861
  rhythmicContrast: 0.22312605218030512
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  lightness: 0.39881320856511593
coverPrefs:
  filter: false
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: 'My Country '
navigation:
  - name: 'Return to One Earth Community '
    url: 'https://thegrid.ai/one-earth-community/'
    type: external
name: 'MyAllAcrossAmerica '
