layout_spectrum: 0.24066231376491487
typography_spectrum: 0.14005537191405892
color:
  saturation: 0.20260974671691656
  brandStrength: 0.0805645789951086
  lightness: 0.3757217931561172
  brandColors:
    - '#10222B'
    - '#95AB63'
    - '#BDD684'
    - '#E2F0D6'
    - '#F6FFE0'
  rhythmicContrast: 0.0931750345043838
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: 'My Country '
navigation:
  - name: 'Return to One Earth Community '
    url: 'https://thegrid.ai/one-earth-community/'
    type: external
name: 'MyAllAcrossAmerica '
