layout_spectrum: 0.20223755459301174
typography_spectrum: 0.3519767145626247
color:
  saturation: 0.9184923339635134
  brandStrength: 0.15564995491877198
  rhythmicContrast: 0.40745212929323316
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  lightness: 0.27970320312306285
coverPrefs:
  filter: false
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: 'My Country '
navigation:
  - name: 'Return to One Earth Community '
    url: 'https://thegrid.ai/one-earth-community/'
    type: external
name: 'MyAllAcrossAmerica '
